### ISSUE TITLE
[BUG] : Neuronbot2_slam중 발생한 data누적 error입니다. 

### ISSUE THREAD

**Issue by ckj0123** [kimsooyoung/neuronbot2_lecture#12]
안녕하세요.
오픈에스지 연구원 최경재입니다.
Neuronbot2_slam의 gmapping, slam_toolbox, cartographer 모두 같은 현상이 발생하고 있으며 아래의 스크린샷은 cartographer입니다.
![Screenshot from 2022-02-25 17-32-56](https://user-images.githubusercontent.com/95273933/155683184-408f3473-7257-40ed-bca9-e9122c77662a.png)
보시는 바와 같이 A1_Lidar를 통한 scan data들이 계속 누적되며 사라지지않는 현상이 발생합니다.(parameter 변경x) 

실행한 프로그램으로는
![Screenshot from 2022-02-25 17-51-45](https://user-images.githubusercontent.com/95273933/155684912-ec4b7127-57b4-4a0f-84a1-111ab3e37de5.png)
![Screenshot from 2022-02-25 17-49-19](https://user-images.githubusercontent.com/95273933/155684543-cffae834-fb66-43b3-93ee-a3c22ac7e63f.png)
1. command : ros2 launch neuronbot2_bringup bringup_launch.py
   (notebook으로 통신 연결하여 뉴런봇의 bringup을 실행하였습니다.)
![Screenshot from 2022-02-25 17-54-00](https://user-images.githubusercontent.com/95273933/155685337-dc52e524-5c46-4ec3-95f9-2d83435808b2.png)
![Screenshot from 2022-02-25 17-54-32](https://user-images.githubusercontent.com/95273933/155685365-74763129-0ecd-43e7-8b2a-3112819a0bb4.png)
![Screenshot from 2022-02-25 17-54-43](https://user-images.githubusercontent.com/95273933/155685390-dab43027-c5b2-46d9-934b-3556aa09b9e4.png)
2. command : ros2 launch neuronbot2_slam cartographer_launch.py open_rviz:=true use_sim_time:=true
![Screenshot from 2022-02-25 17-56-17](https://user-images.githubusercontent.com/95273933/155685594-59879410-fe71-4e73-8bc6-e581117953aa.png)
3. command : ros2 run teleop_twist_keyboard teleop_twist_keyboard

 Environment 사용환경
 - OS Version :  ubuntu18.04LTS 
 - ROS Version : ros2 eloquent

ros2 mapping 2Dlidar sensor data accumulated 및 ros2 mapping cartographer 2d lidar sensor error 등 여러 방면으로 구글링했지만 원하는 정보를 얻지 못했습니다. 
Lidar 및 slam 관련된 parameter들과 link이름은 변경하지 않았습니다.

**Comment by kimsooyoung** [comment]
실제 동작 환경이 어떠한지 알 수 없지만, 큰 벽과 장애물들은 잘 파악된 상황으로 보입니다. 

본디 모든 SLAM들은 작은 물체 하나라도 탐지될 시 해당 장애물을 저장하게 됩니다. 

Loop Closure를 통해 장애물이 없음을 인지시킬 수 있지만 그 과정에서 전체 지도가 틀어질 우려가 있어 비추천하며

**SLAM을 먼저 하고 나서 이미지 툴을 통해 지도를 수정하는 방식을 추천드립니다.**

**Comment by ckj0123** [comment]
통신 문제로 발생한 data누적 현상이었습니다.

통신을 원활히 하니 해당 문제가 해결됬으며, 현재 mapping 후 image_tool을 이용해 수정하는 방식으로 map을 완성했습니다.

신경 써 주셔서 감사합니다.

**Comment by kimsooyoung** [comment]
확인하였습니다. 잘 되었다니 다행입니다 😊
