### ISSUE TITLE
[BUG] : [lifecycle_manager_navigation]: Failed to change state for node: controller_server

### ISSUE THREAD

**Issue by ckj0123** [kimsooyoung/neuronbot2_lecture#14]
![Screenshot from 2022-03-11 13-06-05](https://user-images.githubusercontent.com/95273933/157803837-2bb8aae4-5310-4684-aa82-7c94846ad562.png)
gazebo를 활용하여 model 파일을 생성한 후 로봇 경로 설정을 통해 neuronbot2를 비치한 world파일을 생성하였습니다.
명령어 : ros2 launch neuronbot2_gazebo neuronbot2_world.launch.py world_model:=neuronbot2_lobby.model

![Screenshot from 2022-03-11 13-48-15](https://user-images.githubusercontent.com/95273933/157804004-a3a9d9d7-e1bc-47b5-80f7-635a864c28af.png)
그리고 slam_toolbox를 이용하여 이를 맵핑하였습니다.
명령어 : ros2 launch neuronbot2_slam slam_toolbox_launch.py

![Screenshot from 2022-03-11 13-41-25](https://user-images.githubusercontent.com/95273933/157804268-e7e72003-68bb-42e5-b3cb-9aa2654bb4b5.png)
gazebo를 실행시켰을 때의 terminal입니다.

![Screenshot from 2022-03-11 13-42-18](https://user-images.githubusercontent.com/95273933/157804308-96ccee3c-b026-4d05-a2f5-3cdb1d46e1b1.png)
![Screenshot from 2022-03-11 13-42-33](https://user-images.githubusercontent.com/95273933/157804412-f776989e-72cb-46b3-adc2-4cfcda752040.png)
명령어 : ros2 launch neuronbot2_nav bringup_launch.py open_rviz:=true 를 했을 경우 navigation 단에서 error가 발생하게 되고

![Screenshot from 2022-03-11 13-43-15](https://user-images.githubusercontent.com/95273933/157804449-c30cf742-d511-4853-b8f2-8d42b0ec50a3.png)
다음과 같이 맵에 robot은 생성되나 global & local costmap data를 얻지 못하는 상황입니다.

![Screenshot from 2022-03-11 13-55-30](https://user-images.githubusercontent.com/95273933/157804676-02549819-c675-43ec-b694-d86637ab53c2.png)
ros2 topic list를 검색하였을 경우 각각의 costmap topic이 생성됨도 확인 할 수 있습니다.

![Screenshot from 2022-03-11 13-43-34](https://user-images.githubusercontent.com/95273933/157804881-15303be4-1013-4954-b52c-4f65884f9fa8.png)
neuronbot2_nav의 bringup_launch.py 코드에서도 map파일의 이름을 변경하였습니다.

![Screenshot from 2022-03-11 13-44-22](https://user-images.githubusercontent.com/95273933/157804972-75a00ab8-1a96-4628-a39d-01a1a7b5fbb7.png)
neuronbot2_nav의 localization_launch.py 코드에서도 map파일의 이름을 변경하였습니다.

![Screenshot from 2022-03-11 13-43-47](https://user-images.githubusercontent.com/95273933/157805069-6fe9f4b6-5d07-4a0f-92e5-0526bdd9c1c8.png)
yaml파일에서도 이름을 확인하였습니다.

navigation단에서 error가 발생한 것 같습니다만 googling을 하여도 자세한 답변이 나오지않으며 통신 문제라는 말이 간혹 나오긴 하는 걸로 확입니다.

(windows에서는 다음과 같이 환경설정을 하였을 경우 정상적으로 작동합니다.)

사용환경
 - OS Version : ubuntu18.04
 - ROS Version : ROS2 eloquent

**Comment by kimsooyoung** [comment]
`rqt_graph`를 통해 node간 올바른 데이터 송수신이 이루어지고 있는지 확인해보시고, 
navigation으로 바로 가지 마시고, amcl 부터 확인을 부탁드립니다.

**Comment by ckj0123** [comment]
![Screenshot from 2022-03-15 18-07-33](https://user-images.githubusercontent.com/95273933/158344324-dce0a52e-e79e-4269-81b1-d3ef1726583e.png)
rqt_graph현황입니다. 뭔가 global_costmap과 local_costmap이 map topic과 연결되어있어야 할 거 같은데 연결이 안되있네요..
또 move_base관련 topic들도 보이지 않네요.

![Screenshot from 2022-03-15 18-13-55](https://user-images.githubusercontent.com/95273933/158344995-f701e89a-b396-469b-b127-44939398ebf4.png)
amcl부 확인했을때는 map_file도 slam_lobby.yaml로 바꿔놨는데도 그대로 입니다. 
혹시 amcl parameter를 확인해야 하는 건가요??

**Comment by kimsooyoung** [comment]
1. 기존 예제를 실행시키고 `rqt_graph`를 동일하게 살펴보신 뒤 연결되지 않는 부분이 어디인지, topic 이름이 바뀌지는 않았는지 등을 비교해보시기 바랍니다.
2. gazebo 실행 시, 기존 예제와 차이나는 topic이 있는지 확인하시기 바랍니다.

**Comment by ckj0123** [comment]
![Screenshot from 2022-03-16 17-51-36](https://user-images.githubusercontent.com/95273933/158552349-e28f2bfb-55ac-4415-8eec-530e7ffc30d5.png)
감사합니다. 해결했습니다. global_costmap의 voxel_layer문제였습니다.
